"""Validate ground truth and emit data files for the C++ solver.

Outputs:
  data/pieces.txt : 256 lines "num u r d l" (motif indices 0..22, std order)
  data/clues.txt  : 5 lines "cell piece rotation" (cell row-major, rot cw vs pieces.txt)
  src/e2data.h    : same data embedded as C++ header
Prints a validation report of all reference solutions.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from e2lib import (E2Data, score_edges, check_piece_set, rot_quad, canon,
                   N_CELLS, ROOT)


def main():
    data = E2Data()
    print("== Letter maps derived ==")
    print("jef->std:", "".join(data.jef_to_std[c] for c in sorted(data.jef_to_std)))
    print("jbw->std:", "".join(data.jbw_to_std[c] for c in sorted(data.jbw_to_std)))

    # --- Validate reference boards ---
    print("\n== Reference solutions ==")
    ref_expect = {
        "Joshua_Blackwood_470": 470,
        "JBlackwood+Jef_470": 470,
        "JBlackwood+PMcGavin_469": 469,
        "JBlackwood+Jef_469_a": 469,
        "Joshua_Blackwood_468": 468,
        "Louis_Verhaard_467": 467,
        "Louis_Verhaard_467_a": 467,
    }
    boards_std = {}
    for name, params in data.puzzles.items():
        edges = params.get("board_edges", "")
        if len(edges) != N_CELLS * 4 or name in ("Clues",):
            continue
        if "aaaa" in edges[:64]:
            continue  # partial boards (230 etc.)
        std = data.board_to_std(edges, params.get("motifs_order"))
        score, conf, berr = score_edges(std)
        try:
            placements = check_piece_set(data, std)
            pieces_ok = "pieces OK"
        except ValueError as e:
            placements = None
            pieces_ok = f"PIECES BAD: {e}"
        exp = ref_expect.get(name)
        flag = ""
        if exp is not None:
            flag = "  [OK]" if score == exp else f"  [MISMATCH expected {exp}]"
        print(f"{name:32s} score={score}/480 border_err={berr} {pieces_ok}{flag}")
        if placements:
            boards_std[name] = (std, placements)

    # --- Clues ---
    print("\n== Clues ==")
    cl = data.puzzles["Clues"]
    std = data.board_to_std(cl["board_edges"], cl.get("motifs_order"))
    nums = cl["board_pieces"]
    clues = []
    for s in range(N_CELLS):
        p = int(nums[s * 3:s * 3 + 3])
        if p:
            quad = std[s * 4:s * 4 + 4]
            pid, rot = data.identify(quad)
            assert pid == p, f"clue at cell {s}: quad says piece {pid}, URL says {p}"
            clues.append((s, p, rot, quad))
            print(f"cell {s:3d} (row {s//16}, col {s%16}) piece {p:3d} rot {rot} quad {quad}")
    assert any(p == 139 and s == 135 for s, p, _, _ in clues), "center clue must be piece 139 at cell 135"

    # --- Check which reference boards honor the clues ---
    print("\n== Clue conformance of references ==")
    for name, (bstd, plc) in boards_std.items():
        ok = []
        for s, p, rot, quad in clues:
            ok.append("Y" if bstd[s * 4:s * 4 + 4] == quad else "n")
        print(f"{name:32s} clues[208,255,139,181,249 order as listed]: {''.join(ok)}")

    # --- Emit data files ---
    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    with open(os.path.join(ROOT, "data", "pieces.txt"), "w") as f:
        for p in range(1, 257):
            q = data.piece_quad[p]
            f.write(f"{p} {' '.join(str(ord(c) - 97) for c in q)}\n")
    with open(os.path.join(ROOT, "data", "clues.txt"), "w") as f:
        for s, p, rot, quad in clues:
            f.write(f"{s} {p} {rot}\n")

    # --- Emit C++ header ---
    lines = []
    lines.append("// Auto-generated by tools/make_data.py from reference/bucas_init.js")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("namespace e2 {")
    lines.append("inline constexpr int W = 16, H = 16, N_CELLS = 256, N_COLORS = 23;")
    lines.append("// pieces[p][0..3] = Up,Right,Down,Left motifs of piece p+1 (0-based array)")
    lines.append("inline constexpr uint8_t PIECE_DEFS[256][4] = {")
    row = []
    for p in range(1, 257):
        q = data.piece_quad[p]
        row.append("{" + ",".join(str(ord(c) - 97) for c in q) + "}")
        if p % 8 == 0:
            lines.append("  " + ",".join(row) + ("," if p < 256 else ""))
            row = []
    lines.append("};")
    lines.append("// clue placements: cell (row-major), piece (1-based), cw rotation")
    lines.append("inline constexpr int N_CLUES = %d;" % len(clues))
    lines.append("inline constexpr int CLUES[%d][3] = {" % len(clues))
    for s, p, rot, quad in clues:
        lines.append(f"  {{{s},{p},{rot}}},")
    lines.append("};")
    lines.append("} // namespace e2")
    with open(os.path.join(ROOT, "src", "e2data.h"), "w") as f:
        f.write("\n".join(lines) + "\n")

    print("\nWrote data/pieces.txt, data/clues.txt, src/e2data.h")

    # --- Piece stats sanity ---
    from collections import Counter
    cnt = Counter()
    types = Counter()
    for p in range(1, 257):
        q = data.piece_quad[p]
        g = q.count("a")
        types[g] += 1
        for c in q:
            cnt[c] += 1
    print(f"\npiece types: corners={types[2]} edges={types[1]} interior={types[0]}")
    print(f"grey half-edges: {cnt['a']} (expect 64)")
    odd = [c for c, n in cnt.items() if n % 2]
    print(f"colors with odd counts: {odd if odd else 'none'} (expect none)")


if __name__ == "__main__":
    main()
